### ISSUE TITLE
Onboard Tutorial somehow not working

### ISSUE THREAD

**Issue by kaffarell** [honzaap/Systemizer#34]
Maybe I am just not seeing it, but I am not able to advance to the next tip/tutorial in the onboard tutorial. Shouldn't there be a "next" button or something?

ps: really nice project!

**Comment by honzaap** [comment]
Yeah, there are buttons to go to next and previous. I think it's probably related to screen size since it changes the font size and the larger text pushes the "next" and "previous" button outside. I will fix it today when I get to it.

**Comment by kaffarell** [comment]
Ok, have seen them now, had to zoom in a little bit...

**Comment by honzaap** [comment]
It should be fixed
