### ISSUE TITLE
Feature Suggestion: Heatmap & Repeat Message Frequency

### ISSUE THREAD

**Issue by bradgyton** [honzaap/Systemizer#39]
Firstly. Throw up a buy me a coffee link or something. This is a great tool. As an architect I will be starting to use this daily!

I think a great feature would be a heatmap overlay. Distributed systems often have bottlenecks. If a red haze started to appear around those components that were receiving the most messages in a given timeframe/message ratio, then teams could consider their volumetrics during solution design and cater for an appropriate implementation pattern or consider scale/resource requirements of underlying infrastructure (for those of us stuck on premise anyway 😢 )

It would also be great to set the frequency of sending messages. I.e. client A may be 1 message per second. Client B might be 50 messages per second

**Comment by honzaap** [comment]
Hi, thanks for all the amazing feedback, I wanted to add new features for some time but could't think of anything. I will give it a try, the Client frequency is comming 100% though, don't know why did I not add it in the start.
