### ISSUE TITLE
Great start! But why doesn't HTTP Web Server have outputs?

### ISSUE THREAD

**Issue by briantully** [honzaap/Systemizer#44]
In my experience it is rare for a web server not to have outputs to external endpoints. In the case of most CMS, the web server accepts the initial request, but then makes a request to the database and/or an external API to get data associated with the route/path of the HTTP request. 

However, unless I am mistaken, Systemizer doesn't seem to be able to illustrate this common scenario as the HTTP Web Server component has no outputs.

Would it make sense to allow Web Server components to have outputs so that the flow between Web Server and Database is 2-way? Otherwise it seems that I'd have to connect the load balancer directly to the database first, which isn't exactly representative.

Thanks again for such a promising and fun tool!

**Comment by honzaap** [comment]
I get a lot of comments about this, I'll change it to have output aswell.
