### ISSUE TITLE
Future plans for the project?

### ISSUE THREAD

**Issue by Ibrahim-Islam** [honzaap/Systemizer#59]

**Comment by honzaap** [comment]
I'm sorry but I don't plan on working on this project for some time, I will review/merge PR's if there are some but I don't have the time or energy to work on this project right now.

**Comment by Ibrahim-Islam** [comment]
You have done a great job. I see a lot of potential for the project. How about setting this up in an organization and open it up for maintainers?

**Comment by honzaap** [comment]
I know it's a shame to ditch the project like this... some help from other people would be great. I'll look into it. Thanks

**Comment by Ibrahim-Islam** [comment]
If you need a hand with anything. Let me know 🤝
